// <auto-generated />
namespace ChannelRankings.Data.PostgreSQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class deletedsomestuff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deletedsomestuff));
        
        string IMigrationMetadata.Id
        {
            get { return "201706120956245_deleted some stuff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
