// <auto-generated />
namespace ChannelRankings.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removedIpersoninterface : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedIpersoninterface));
        
        string IMigrationMetadata.Id
        {
            get { return "201706051601401_removed Iperson interface"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
