// <auto-generated />
namespace ChannelRankings.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UsedFluentAPIforconstrainingSponsormodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UsedFluentAPIforconstrainingSponsormodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201706041834540_Used Fluent API for constraining Sponsor model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
